const cities = [
  "Aachen",
  "Augsburg",
  "Berlin",
  "Bergisch Gladbach",
  "Bielefeld",
  "Bochum",
  "Bonn",
  "Bottrop",
  "Braunschweig",
  "Bremerhaven",
  "Bremen",
  "Chemnitz",
  "Cottbus",
  "Darmstadt",
  "Dortmund",
  "Dresden",
  "Duisburg",
  "Düsseldorf",
  "Düren",
  "Erfurt",
  "Erlangen",
  "Essen",
  "Esslingen",
  "Esslingen am Neckar",
  "Flensburg",
  "Frankfurt",
  "Frankfurt am Main",
  "Freiburg",
  "Freiburg im Breisgau",
  "Fürth",
  "Gelsenkirchen",
  "Gera",
  "Gießen",
  "Göttingen",
  "Gütersloh",
  "Hagen",
  "Halle",
  "Hamburg",
  "Hamm",
  "Hanau",
  "Heidelberg",
  "Heilbronn",
  "Herne",
  "Hildesheim",
  "Ingolstadt",
  "Iserlohn",
  "Jena",
  "Kaiserslautern",
  "Karlsruhe",
  "Kassel",
  "Kiel",
  "Koblenz",
  "Köln",
  "Konstanz",
  "Krefeld",
  "Leverkusen",
  "Ludwigshafen",
  "Ludwigshafen am Rhein",
  "Ludwigsburg",
  "Lübeck",
  "Lünen",
  "Magdeburg",
  "Mainz",
  "Mannheim",
  "Marl",
  "Moers",
  "Mönchengladbach",
  "Mülheim",
  "Mülheim an der Ruhr",
  "München",
  "Münster",
  "Neuss",
  "Nürnberg",
  "Oberhausen",
  "Offenbach",
  "Offenbach am Main",
  "Oldenburg",
  "Osnabrück",
  "Paderborn",
  "Pforzheim",
  "Potsdam",
  "Ratingen",
  "Regensburg",
  "Remscheid",
  "Reutlingen",
  "Rostock",
  "Saarbrücken",
  "Salzgitter",
  "Schwerin",
  "Siegen",
  "Solingen",
  "Stuttgart",
  "Trier",
  "Tübingen",
  "Ulm",
  "Villingen-Schwenningen",
  "Wiesbaden",
  "Witten",
  "Wolfsburg",
  "Worms",
  "Wuppertal",
  "Würzburg",
  "Zwickau",
];

export default cities;
