const cities = [
  "A Coruña",
  "Albacete",
  "Alcalá de Henares",
  "Alcobendas",
  "Alcorcón",
  "Algeciras",
  "Alicante",
  "Almería",
  "Arrecife",
  "Avilés",
  "Ávila",
  "Badajoz",
  "Badalona",
  "Barakaldo",
  "Barcelona",
  "Benalmádena",
  "Benidorm",
  "Bilbao",
  "Burgos",
  "Cáceres",
  "Cádiz",
  "Cartagena",
  "Castellón de la Plana",
  "Chiclana de la Frontera",
  "Ciudad Real",
  "Córdoba",
  "Cornellà de Llobregat",
  "Cuenca",
  "Dos Hermanas",
  "El Ejido",
  "El Puerto de Santa María",
  "Elche",
  "Elda",
  "Estepona",
  "Ferrol",
  "Fuengirola",
  "Fuenlabrada",
  "Gandía",
  "Getafe",
  "Gijón",
  "Girona",
  "Granada",
  "Huelva",
  "Jaén",
  "Jerez de la Frontera",
  "L'Hospitalet de Llobregat",
  "Las Palmas de Gran Canaria",
  "Leganés",
  "León",
  "Linares",
  "Lleida",
  "Logroño",
  "Lorca",
  "Lugo",
  "Madrid",
  "Málaga",
  "Manresa",
  "Marbella",
  "Mataró",
  "Móstoles",
  "Murcia",
  "Orihuela",
  "Ourense",
  "Oviedo",
  "Palencia",
  "Palma de Mallorca",
  "Pamplona",
  "Parla",
  "Ponferrada",
  "Pontevedra",
  "Pozuelo de Alarcón",
  "Reus",
  "Roquetas de Mar",
  "Sabadell",
  "Salamanca",
  "San Cristóbal de La Laguna",
  "San Fernando",
  "San Sebastián",
  "San Vicente del Raspeig",
  "Santa Coloma de Gramenet",
  "Santa Cruz de Tenerife",
  "Santander",
  "Santiago de Compostela",
  "Segovia",
  "Sevilla",
  "Talavera de la Reina",
  "Tarragona",
  "Telde",
  "Terrassa",
  "Toledo",
  "Torrejón de Ardoz",
  "Torrent",
  "Torrevieja",
  "Valencia",
  "Valladolid",
  "Vélez-Málaga",
  "Vigo",
  "Vitoria-Gasteiz",
  "Zamora",
  "Zaragoza",
];

export default cities;
