const France = [
  "Aix-en-Provence",
  "Ajaccio",
  "Amiens",
  "Angers",
  "Annecy",
  "Antibes",
  "Antony",
  "Argenteuil",
  "Asnières-sur-Seine",
  "Aubervilliers",
  "Aulnay-sous-Bois",
  "Avignon",
  "Besançon",
  "Béziers",
  "Bordeaux",
  "Boulogne-Billancourt",
  "Brest",
  "Caen",
  "Cannes",
  "Cayenne",
  "Chambéry",
  "Champigny-sur-Marne",
  "Cherbourg-en-Cotentin",
  "Clermont-Ferrand",
  "Colmar",
  "Colombes",
  "Courbevoie",
  "Créteil",
  "Clichy",
  "Dijon",
  "Drancy",
  "Dunkerque",
  "Fort-de-France",
  "Grenoble",
  "Ivry-sur-Seine",
  "Issy-les-Moulineaux",
  "La Rochelle",
  "La Seyne-sur-Mer",
  "Le Blanc-Mesnil",
  "Le Havre",
  "Le Mans",
  "Le Tampon",
  "Levallois-Perret",
  "Limoges",
  "Lille",
  "Lorient",
  "Lyon",
  "Maisons-Alfort",
  "Mamoudzou",
  "Marseille",
  "Mérignac",
  "Metz",
  "Montauban",
  "Montpellier",
  "Montreuil",
  "Mulhouse",
  "Nancy",
  "Nanterre",
  "Nantes",
  "Nîmes",
  "Niort",
  "Noisy-le-Grand",
  "Nouméa11",
  "Orléans",
  "Pantin",
  "Paris",
  "Pau",
  "Perpignan",
  "Pessac",
  "Poitiers",
  "Quimper",
  "Reims",
  "Rennes",
  "Roubaix",
  "Rouen",
  "Rueil-Malmaison",
  "Saint-Denis",
  "Saint-Étienne",
  "Saint-Maur-des-Fossés",
  "Saint-Nazaire",
  "Saint-Paul",
  "Saint-Pierre",
  "Sarcelles",
  "Strasbourg",
  "Toulon",
  "Toulouse",
  "Tourcoing",
  "Tours",
  "Troyes",
  "Valence",
  "Vénissieux",
  "Versailles",
  "Villeurbanne",
];

export default France;
