const cities = [
  "Alkmaar",
  "Almelo",
  "Almere",
  "Alphen aan den Rijn",
  "Amersfoort",
  "Amsterdam",
  "Amstelveen",
  "Apeldoorn",
  "Arnhem",
  "Assen",
  "Barneveld",
  "Barendrecht",
  "Bergen op Zoom",
  "Beverwijk",
  "Breda",
  "Capelle aan den IJssel",
  "Castricum",
  "Culemborg",
  "De Fryske Marren",
  "Delft",
  "Den Bosch",
  "Den Haag",
  "Den Helder",
  "Deventer",
  "Doetinchem",
  "Dordrecht",
  "Drachten",
  "Dronten",
  "Ede",
  "Eindhoven",
  "Emmen",
  "Enschede",
  "Gorinchem",
  "Gouda",
  "Groningen",
  "Haarlem",
  "Haarlemmermeer",
  "Hardenberg",
  "Harderwijk",
  "Heerenveen",
  "Heerhugowaard",
  "Heerlen",
  "Hellevoetsluis",
  "Helmond",
  "Hendrik-Ido-Ambacht",
  "Hengelo",
  "Hilversum",
  "Hoeksche Waard",
  "Hoogeveen",
  "Hoorn",
  "Huizen",
  "IJsselstein",
  "Kampen",
  "Kerkrade",
  "Leeuwarden",
  "Leiden",
  "Leidschendam-Voorburg",
  "Lelystad",
  "Maastricht",
  "Medemblik",
  "Meierijstad",
  "Meppel",
  "Middelburg",
  "Nieuwegein",
  "Nijmegen",
  "Nissewaard",
  "Oosterhout",
  "Oss",
  "Purmerend",
  "Rijswijk",
  "Roermond",
  "Roosendaal",
  "Rotterdam",
  "Schiedam",
  "Sittard-Geleen",
  "Smallingerland",
  "Soest",
  "Súdwest-Fryslân",
  "Tiel",
  "Tilburg",
  "Uden",
  "Utrecht",
  "Veenendaal",
  "Veldhoven",
  "Velsen",
  "Venlo",
  "Venray",
  "Vlaanderen",
  "Vlaardingen",
  "Waalwijk",
  "Wageningen",
  "Weert",
  "Westland",
  "Woerden",
  "Zaanstad",
  "Zeist",
  "Zoetermeer",
  "Zutphen",
  "Zwolle",
];

export default cities;
