const polishCities = [
  "Bełchatów",
  "Będzin",
  "Biała Podlaska",
  "Białystok",
  "Bielsko-Biała",
  "Bolesławiec",
  "Bydgoszcz",
  "Bytom",
  "Chełm",
  "Chorzów",
  "Ciechanów",
  "Częstochowa",
  "Dąbrowa Górnicza",
  "Elbląg",
  "Ełk",
  "Gdańsk",
  "Gdynia",
  "Gliwice",
  "Głogów",
  "Gniezno",
  "Gorzów Wielkopolski",
  "Grudziądz",
  "Inowrocław",
  "Jastrzębie-Zdrój",
  "Jaworzno",
  "Jelenia Góra",
  "Kalisz",
  "Katowice",
  "Kędzierzyn-Koźle",
  "Kielce",
  "Konin",
  "Koszalin",
  "Kraków",
  "Krosno",
  "Kutno",
  "Legionowo",
  "Legnica",
  "Leszno",
  "Lubin",
  "Lublin",
  "Łomża",
  "Łódź",
  "Mielec",
  "Mysłowice",
  "Nowy Sącz",
  "Nysa",
  "Olsztyn",
  "Opole",
  "Ostrów Wielkopolski",
  "Ostrowiec Świętokrzyski",
  "Oświęcim",
  "Otwock",
  "Pabianice",
  "Piekary Śląskie",
  "Piła",
  "Piotrków Trybunalski",
  "Płock",
  "Poznań",
  "Przemyśl",
  "Pruszków",
  "Puławy",
  "Racibórz",
  "Radom",
  "Radomsko",
  "Ruda Śląska",
  "Rybnik",
  "Rzeszów",
  "Siedlce",
  "Siemianowice Śląskie",
  "Skarżysko-Kamienna",
  "Skierniewice",
  "Słupsk",
  "Sochaczew",
  "Sosnowiec",
  "Stalowa Wola",
  "Starachowice",
  "Stargard",
  "Starogard Gdański",
  "Suwałki",
  "Szczecin",
  "Świdnica",
  "Świętochłowice",
  "Tarnowskie Góry",
  "Tarnów",
  "Tczew",
  "Tomaszów Mazowiecki",
  "Toruń",
  "Tychy",
  "Wałbrzych",
  "Warszawa",
  "Wejherowo",
  "Włocławek",
  "Wrocław",
  "Zabrze",
  "Zamość",
  "Zawiercie",
  "Zduńska Wola",
  "Zgierz",
  "Zielona Góra",
  "Żory",
];

export { polishCities };