const Portugal = [
  "Abrantes",
  "Águeda",
  "Albufeira",
  "Alcobaça",
  "Alenquer",
  "Almada",
  "Amarante",
  "Anadia",
  "Angra do Heroísmo",
  "Aveiro",
  "Barcelos",
  "Barreiro",
  "Beja",
  "Benavente",
  "Braga",
  "Bragança",
  "Caldas da Rainha",
  "Câmara de Lobos",
  "Cantanhede",
  "Cascais",
  "Castelo Branco",
  "Chaves",
  "Coimbra",
  "Covilhã",
  "Évora",
  "Espinho",
  "Esposende",
  "Estarreja",
  "Fafe",
  "Faro",
  "Felgueiras",
  "Figueira da Foz",
  "Funchal",
  "Fundão",
  "Gondomar",
  "Guarda",
  "Guimarães",
  "Ílhavo",
  "Lagoa",
  "Lagos",
  "Leiria",
  "Lisboa",
  "Lagoa",
  "Lourinhã",
  "Lousada",
  "Loures",
  "Maia",
  "Marco de Canaveses",
  "Marinha Grande",
  "Matosinhos",
  "Mafra",
  "Montijo",
  "Moita",
  "Odemira",
  "Odivelas",
  "Oeiras",
  "Olhão",
  "Oliveira de Azeméis",
  "Oliveira do Bairro",
  "Ourém",
  "Paços de Ferreira",
  "Palmela",
  "Paredes",
  "Penafiel",
  "Peniche",
  "Ponta Delgada",
  "Portimão",
  "Porto",
  "Póvoa de Varzim",
  "Ribeira Grande",
  "Santa Cruz",
  "Santa Maria da Feira",
  "Santarém",
  "Santiago do Cacém",
  "Santo Tirso",
  "Seixal",
  "Setúbal",
  "Silves",
  "Sintra",
  "Sesimbra",
  "Tomar",
  "Tondela",
  "Torres Novas",
  "Torres Vedras",
  "Trofa",
  "Tavira",
  "Valongo",
  "Viana do Castelo",
  "Vila Franca de Xira",
  "Vila Nova de Famalicão",
  "Vila Nova de Gaia",
  "Vila Real",
  "Vila Verde",
  "Vila do Conde",
  "Viseu",
];

export default Portugal;
