const cities = [
  "Aberdeen",
  "Basingstoke",
  "Basildon",
  "Bath",
  "Bedford",
  "Becontree",
  "Belfast",
  "Birkenhead",
  "Birmingham",
  "Blackburn",
  "Blackpool",
  "Bolton",
  "Bournemouth",
  "Bradford",
  "Brighton",
  "Bristol",
  "Cambridge",
  "Cardiff",
  "Chelmsford",
  "Cheltenham",
  "Colchester",
  "Coventry",
  "Crawley",
  "Dagenham",
  "Darlington",
  "Derby",
  "Derry",
  "Dudley",
  "Dundee",
  "Eastbourne",
  "Edinburgh",
  "Exeter",
  "Gillingham",
  "Glasgow",
  "Gloucester",
  "Halifax",
  "Harlow",
  "Harrogate",
  "Hartlepool",
  "Hemel Hempstead",
  "Huddersfield",
  "Hull",
  "Ipswich",
  "Islington",
  "Leeds",
  "Leicester",
  "Lincoln",
  "Liverpool",
  "Londonderry",
  "London",
  "Luton",
  "Maidstone",
  "Manchester",
  "Mendip",
  "Middlesbrough",
  "Milton Keynes",
  "Newcastle",
  "Newport",
  "Northampton",
  "Norwich",
  "Nottingham",
  "Oldham",
  "Oxford",
  "Peterborough",
  "Plymouth",
  "Poole",
  "Portsmouth",
  "Preston",
  "Reading",
  "Rochdale",
  "Rotherham",
  "Saint Albans",
  "Saint Helens",
  "Sheffield",
  "Slough",
  "Solihull",
  "South Shields",
  "Southampton",
  "Southend-on-Sea",
  "Stoke-on-Trent",
  "Sunderland",
  "Sutton",
  "Sutton Coldfield",
  "Swansea",
  "Swindon",
  "Telford",
  "Watford",
  "Walsall",
  "West Bromwich",
  "Weston-super-Mare",
  "Woking",
  "Wolverhampton",
  "Worcester",
  "Worthing",
  "York",
];

export default cities;
